# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed661992c765fc3994c16684399d6daed68af4e73deccd0f710fb182d78557079ff346b3461764e3ba76edf70b1f09529f6b09c7ae1325b9dbe74802430cd57b

test:
  secret_key_base: af406ed841d0b758fbf6e9ce545e49412c435ba2757925a8897393520ef96d5c4f775bb4f1dcca4077ba108c803174a2ebd8803039746271a7fd47fcb6ae1125

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
